# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    prometheus.yml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: malatini <dev@malatini.dev>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/25 12:36:01 by malatini            #+#    #+#              #
#    Updated: 2021/10/25 13:55:14 by malatini           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets: [  'cadvisor:CADVISOR_PORT' ]

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [  'localhost:PROMETHEUS_PORT'  ]