version: "3.8"

#Les variables d'environnement doivent toutes etre dans un fichier .env
#Le tag latest est interdit
#3 grandes sections - les services (=les containers), les networks (=la communication), 
#les volumes (les fichiers/ressources)

#Pour rappel nous travaillons LEMP Stack

#Attention l'indentation est tres important dans un fichier yaml
#les tab conviennent ? ou il va falloir tout mettre avec des espaces ?

#Definir les networks et volumes avant les services ne devrait pas avoir de difference. 

#https://docs.docker.com/compose/networking/
#Si la directive networks n'est pas specifiee, un network sera cree par defaut
#Sinon, nous avons la possibilite de definir plusieurs networks et de
#determiner quels sont les services qui y ont acces
networks:
    inception_network:
        name: inception_network

#https://docs.docker.com/storage/volumes/
#https://www.it-swarm-fr.com/fr/docker/docker-compose.yml-syntaxe-des-volumes-nommes/806987524/
#Volumes are the preferred mechanism for persisting data generated by and used by Docker containers. 
#Volumes are "completely managed by Docker"       
volumes:
        wordpress_data:
                name: wordpress_data
                driver: local
                driver_opts:
                    type: none
                    device: /home/malatini/data/wordpress
                    o: bind
                
        db_data:
                name: db_data
                driver: local
                driver_opts:
                    type: none
                    device: /home/malatini/data/mysql
                    o: bind

#Nos containers/services
#Pour les services, l'ordre a un sens, mais on peut aussi ajouter la directive
#depends_on pour verifier qu'un service soit bien up avant un autre 
#pour eviter des erreurs de connectivite ou autres
#meme si les variables d'environnement sont dans le .env il faut quand meme 
#proceder a l'"interpolation" de celles ci".
services:
        mariadb:
            container_name: mariadb
            #build va indiquer ou trouver l'image a builder
            build: ./requirements/mariadb
            environnement:
             - MYSQL_DATABASE=${MYSQL_DATABASE}
             - MYSQL_USER=${MYSQL_USER}
             - MYSQL_PASSWORD={MYSQL_PASSWORD}
             - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            volumes:
            #Attention a bien mapper avec un volumes qui a ete defini plus haut 
            #via la directive volumes
             - db_data:/var/lib/mysql
            networks:
             - inception_network
            #on a pas le droit d'utiliser le tag "latest" donc on va specifier le notre
            #pour permettre de le "figer"
            #specifie le nom et la version de l'image
            image: mariadb:inception
            #On map le port de la machine hote sur le port du service
            ports:
             - "3306:3306"
            restart: always
        wordpress:
            #Nous avons besoin que la base de donnees soit prete avant que wordpress puisse etre lance
            depends_on:
                - mariadb
            #Wordpress aurait besoin de se connecter a la base de donnees
            #et d'interagir avec elle, il nous faut donc les variables d'environnements egalement dans ce service
            environnement:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD={MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            #Il est demande dans le sujet que les containers portent les memes noms que les services
            container_name: wordpress
            build: ./requirements/wordpress
            image: wordpress:inception
            volumes:
                - wordpress_data:/var/www/html/wordpress
            networks:
                - inception_network
            ports:
             - "9000:9000"
            restart: always
        nginx:
            depends_on:
                - wordpress
            container_name: nginx
            build: ./requirements/nginx
            image: nginx:inception
            #Only accessible port (from the outside, even outside the computer host)
            ports:
                - "443:443"
            volumes:
                - wordpress_data:/var/www/html/wordpress
            networks:
                - inception_network
            restart: always