version: '3.6'

# Les volumes sont utilises pour la persistances des donnees
# https://docs.docker.com/storage/volumes/

services:
  nginx:
    container_name: nginx
    # Ne va pas essayer de se build si wordpress n'a pas reussi a se build
    depends_on:
     - wordpress
    # Path to the directory which contains the Dockerfile (could be a url)
    build:
      context: ./requirements/nginx
    #On donne un nom a l'image qui va etre utilisee pour le build
    # Liste des volumes auxquelles le container a acces (peut partager avec d'autres)
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception-network
    # defines mapping between the host and the container.
    # On ne veut pas faire ca sur les autres containers puisque seul ce port doit etre accessible.
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception-network
    # Interpolation des variables d'environnement
    environment:
      - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception-network
    # Variables d'environnement pour la configuration du Wordpress + acces a la base de donnees
    environment: 
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
    restart: on-failure

volumes:
  mariadb-volume:
  # "driver specifies a logging driver for the service's container"
  # local means the volume are created on the same Docker host on which the containers are running.
  # we could create volumes on external hosts.
  # Par defaut sur linux les volumes sont montes sur /var/lib/docker/volumes/
    driver: local
    # Les trois options sont necessaires sinon le build ne fonctionne pas
    driver_opts:
    #   # Les volumes doivent se trouver dans ce dossier sur la machine hote.
    #   # Demande express du sujet
      device: /home/malatini/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/malatini/data/wordpress
      type: volume
      o: bind

# Definition de notre network (comme sur le schema d'architecture)
# Les containers seront reachable uniquement par les autres containers du meme reseau
# Par defaut docker cree un reseau meme si rien n'est specifie
# La directive doit etre mentionnee (selon le sujet).
networks:
  inception-network: