version: '3'
 
networks:
  frontend:
  backend:

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    #image: img_nginx
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - frontend
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    build: ./requirements/wordpress
    #image: img_wordpress
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - frontend
      - backend
    environment: 
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #image: img_mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    restart: always